#+title: CS120 Lab *10* Section *4*
#+author: Heyan Huang
#+startup: beamer
#+latex_class: beamer
#+options: H:1 num:t toc:nil

* Fairwell

Hello Tower iLLuminati, 

Every party has to come to an end, and here it comes. 

I have been much elder than you, and I have had way more experiences than you in industry, and that may be some reason that towrads my work and priject, sometimes I was way too restricted, though I tried my best to understand that you guys have compilers. 

Since I donesn't fit the team and your culture that well, right now I was aksed to desin the project independent from you guys, and as far as the department is concerned, I am completely ok with it. During this period of time, I am not allowed to talk to our client than expected, I am not allowed to ask more detailed questions with you guys, unless I am going to ask questions when I have difficulties as I am a CS majored students, and I have the right to ask questions towards you guys whoever works in CSAC.
 
* footprint

Hello Emeth, and the related department, 

As I pointed out that it was all your fault which leaded to these whole confusion, and have stated in the meeting on Saturday that, I was going to write a email as a footprint to prevent you from future suffering, and help myself clear my life here in U of I. 

Facts:

- On team meeting *10/7/2014, Tuesday*, always being active and fast towards projects, Matt suggested us to install Qt Creator, downloaded Qt Creator sample codes into github. He helped Paul installed the software on Windows, and I did mine in Linux. Matt's sample code created and menu bar "File" command already, and "Exit" from submenu of "File". 
- On team meeting *10/7/2014*, the same Tuesday meeting, you excused yourself having trouble with MS c++ IDE, and would do rather the IDE package than the independent Qt Creator, and Ranger spontaneously offered helped to you that he was going to help you look into MS c++ IDE if you needs any help. 
  
- On team meeting *10/7/2014*, the same Tuesday meeting, Matt, Paul and me got our Qt environment ready, while Ranger and you chatted and talked about your compilers, and draw the "Design Flowchart" on whiteboard and listed, "C# prototypes organized uml diagrams, prototypes/language training Diagrams", and assigned to Ranger dated "by coming Tuesday Ranger", deadline 10/21/2014; "Design/Docs/Exact Class Diagrams" deadline 11/11/2014; 
  
- On team meeting *10/7/2014*, the same Tuesday meeting. In the end of the meeting, as you were the respected one with full communications with course instructors, and could draw exact deadlines like listed above, when asked about tasks before next meeting for Qt Creator coding training part, you clearly stated as far as we could create one button and exit from there, we are good. Matt insisted that "I already did that", but you blocked the whole team from processing by giving no followed up tasks/assignments on Qt Creator. 
  
- On Team meeting *10/9/2014*, the meeting with instructor Professor Bolden, you covered part of the project agenda; and you *begged*/kind of *forced* Ranger to stand into front and speak of something. And Ranger did follow your call and covered parts of the c# codes on color Pale, color wheel, Grid, Main form. I specifically asked if Ranger could draw a clear class diagram for C# design, he looked into Professor Bolden, and the professor gave enough tolerance to Ranger that we didn't necessarily need any class diagrams even you listed it on whiteboard two days ago.  
  
- On *Friday 10/10/2014*, in CSAC between 4:00-5:00pm, I asked if you have base version tower light interface, you said no, and we agreed I sent email to ask help from team members; The same evening I sent two emails out, even call for gathering and preparing for coming Tuesday's snapshot day, as the team manager, you completely ignored my email and leave me no chance to prepare for snapshot day by having asked Paul only (without letting other team member knew about it) to work with you to prepare the snapshot day. And what a probability that our team was completely forgotten by the course instructor as well, not shown at all in the email list the instructors sent out. 
  
- On week *10/12/2014-10/18/2014*, because all of you have compilers, we didn't meet. 
  
 - On Team meeting *10/23/2014, Thursday*, after having checked with Professor Bolden, you listed us on board in Matt's office, that we have assignments need to be done, including state diagram, wiki page, class diagrams, GUI design and description. And Emeth you wanted to work on Wiki page, Matt would work on state diagram, I wanted to work on GUI design, Ranger and you would work on class diagram, and Paul jointed me to work on GUI. You set very high standards on GUI doc name conventions and even suggested that we need to consult some other department, but my sub-team member Paul argued it back that we don't need to. 
   
 - On Team meeting *10/23/2014, Thursday*, In the same meeting when I picked this GUI design assignment, as an always considerable teammate Matt is, he argued me, "do you understand what a GUI design is? -- To create a clickable interface that we as a whole team could link functionalities on the buttons later on.  As far as I understood, I knew clearly what I was supposed to do, as clear as any other team member knew. And nobody ever rejected any of Matt's reminder opinion on the GUI or mine on this GUI design at all. 
   
- On Team meeting *10/28/2014, Tuesday*, I didn't really remember when Matt checked in and uploaded his state diagram onto Google drive, but it should be sometime during this week. We chatted and discussed about some details about merging two paths/pattern. Ranger did draw some pic on the board. In the end, you asked Ranger to send this photo pic to you, and asked from Ranger about the same, but I never received any pic from Ranger yet about that meeting's draw on board. 
  
 - On Team meeting *10/30/2014, Thursday*, by this time, Matt probably has checked in his state diagram already, and we emphasized on Emeth, you work on wiki page by coming Tuesday; and Ranger and Emeth work on class diagram, and Paul and I work on GUI and GUI docs. As Matt has checked in already, and been emphasized and deadline was coming, I set my mind to work on it.
   
 - On *Friday 10/31/2014*, on the mornings somewhere, my sub-team mate Paul taught me how to create form-based Qt Creator interface. I had fun building some buttons. And between 11:30-1:00pm when you showed up in CSAC, I was working on the GUI, and I showed my currently working GUI form-based interface to you. You seemed to feel exact but good or bad, you didn't say anything about it. 
   
- On *11/4/2014, Tuesday*, for the first time, you skipped me from the team meeting with no excuse at all. This wasn't the first time that we skip a meeting. When it was you guys' compiler exam week, we skipped team meeting once. And This was the first time you all moved downstairs to have team meeting in Matt's office instead of in CSAC on Tuesdays, and as the team manager, you leaded the team without notify me about the team meeting. And your coldness in your email freeze my mind, it was like finger pointing and clearly saying that me, as the only one who ever missed the meeting, was the one who didn't do anything at all as you descried Paul to me the followed day. And I was so considerate and tolerate to you by just saying that "your email surprised me a little bit".
  
- On *11/5/2014, Wednesday*, you didn't reply to my Tuesday evening's email and chose to step by our office, and chatted to me for several minutes. During those several minutes, the points you made includes: 
1. Checked me if my sub-team mate Paul was doing anything at all. Almost as motivated as I am, as everybody knew Paul has at least prepared the snapshot day's image design already, so did I, I explicitly emphasized that to me, Paul didn't have such a problem at all, and I always has my full confident on him. 
2. When you insisted that later on you will send email to remind us about meetings, I wanted to make it clear that you didn't necessarily need to send us email at all, but you made a point that Ranger is a person prefer oral works, and doesn't like any reading and writing at all. Yet still you insisted you would send email out so that you could remind Ranger because you need to anyway. 
3. Combined your coldness on 11/4 email and the scene you prepared for me, if later on I wouldn't be able to produce the clickable GUI, I would be basted to death. Could the scene/environment be any colder on me? Why do I need to suffer this?
   
- On *11/6/2014, Thursday*, on the mornings I received Bruce's email and he clearly stated that he will have access to our emails. And I agreed I have no problem with that at all with all my reasonable guess what happened during the mornings. 
  
- On *11/6/2014, Thursday*, since coming Tuesday will be the design review day already, and nobody ever brought up the design review thing ever, nobody! We were mainly on the Ranger's performance thing, and you asked Ranger to try to mimic the presentation in Matt's office without any writing material. And Ranger clearly asked if we could have our GUI interface ready that would be something great. I also wished that I could finish have my interface so that we would be able to demo it, which according to me, would greatly improve our grades as well. As that time, Emeth, you tried to be a considerate manager without giving me any pressure by, simply completely ignore the fact that I have been working on it, and have at least showed it you once, simply clearly stating that if Ranger really think we should have something to demo, Emeth you as the team manager, would simply ask Paul to create a short video to demo the functionalities, which was what happened during the coming weekend. 
  
- On *11/6/2014, Thursday*, after our team meeting, which ended at around 4:30pm, my sub-team mate Paul and I went to CSAC and I asked him about the difficulties that I have, like how to add an image using form-based interface. Together with me, Paul and I used two laptops searched for some time. As frustrated as I was, Paul called you discussed about the difficulties that we encountered, and as the team manager, still you didn't say anything about the clickable GUI design related issues, rather than relax us by stating that we could still simply create an image based interface just like what Paul did already for our snapshot day, as far as it's slightly better, like we agreed that our moving direction should have 8 directions instead of 4. It was 5:00 already, I felt I contributed to the team too limited, and Paul and I agreed that I would work on the image and docs during the weekend, and our sub-team would meet on Monday at 2:30pm to clear work out. It was during weekend when I really worked hard on the GUI, in the email I moved the GUI docs works to Paul so that in sub-team he would be able to contribute as well. 
  
- Before Tuesday's meeting, you have your excuses like you have TA lab section on Tuesday mornings, but you never took your imitative to offer a time like sometime on Monday or weekend to review the slides of Ranger's presentation or offer any guide. 
  
- On *11/11/2014, Tuesday*, Design Review with CS related teams gathered together. Before class, I noticed that Emeth you were asking classmates if they have met any person who didn't know the correct way to communicate in a business manner. And during the day's 5 team presentation, Professor Bolden gave Ranger too long time on our review with Ranger spent half of the time description on feature that I didn't finish on the time Editor. I did feel bad about you guys by behaving like this. Professor Bolden, you and I talked after that days' design review class in the same classroom, but I got sick of the environment already. Professor Bruce said that he didn't read all the emails, I wondered if he "did", could the situation be any better? And at around 4:30, I received email from human resources, whatever the contents are in the email, I felt pressed. 
  
- The followed several days communications were completely a mess, and personally I don't even want to recall all these things. 
  
- On *11/13/2014, Thursday*, you casted a great anger toward the whole team by blaming us that we missed the point of design review, which I have pointed it out on last Sunday's email already but you paid no attention to it, let alone correct us at all. But as far as you recognized in the end of the meeting, you blamed yourself you didn't know what the fxxxxxx you were talking about in the end before leaving the room, I tolerant your anger, forgiven you and didn't make any sound. 
  
- On *11/15/2014, Saturday*, you applied your advantages by taking team meeting notes. You didn't offer any suggestions except that you explicitly specifically blamed that it was my fault misunderstood you. At this point, I cannot tolerant you anymore, and stated to you clearly that it was all your fault by misleading the whole team do wrong things at the wrong time, and I would write to you make this clear to prevent you from repeating such situations. I must be too anger to blame it was you, but actually it could be the department as well, cause you have been the only person keep close relationship with the department, and you were entitled absolute admire by an undergraduate TA. 
  
Emeth, please understand that I never take any initiative to hurt any other person. Whenever I need to stand out to say something, I stand out only when I got very hurt and cannot bear the situation any more. It was you, who was extremely unreasonable, that forced me to stand out, clear everything clean, so that later on I won't suffer any more from these afterwards. You were the source produced all these troubles. 


First of all, I appreciate the TA I got for this fall semester. But please all help to realize the facts that I listed. About the TA: as clear as i demonstrated, I appreciate if I could get it, but I won't be any aggressive to fight for it at all. Maybe I am writing trying to reach global agreement between the department and me. 

1. Early on 10/23/2014, cs120 lab8 section 6, I covered email and demoed emacs presentation slides generation using org-mode, just wanted them get encouraged and learn the command-based editor. When I realize the afterwards influence, with my current advisor fully supported me to demo by design the lab8 to be one easy function only, the coming Tuesday 10/28 (the emacs slides were still left there, but I didn't cover that much and didn't demo org-mode slides generation any more at all), I hide my shining avoid any emacs demo just asked the section 4 to add one line of global-line-number configuration for their convenience. I just wanted to keep low-profile life. 
2. After the unfortunate Emacs thing, Dr. Soule fully supported Josh, the other TA's idea about curses window for assignments. For me, it was just a wrapper class like any other project that I can do. I have my priorities for works to do, I didn't pay enough attention to that, but it was followed by Emeth's aggressiveness by picking my accent. I am perfectly ok with my accent. 
3. Dr. Soule fully supported towards Emeth and Josh, and the assignments extended one week, the students looked down on me, and I have even received "patent" emails during those days. How the environment could possibly appeared to be that way? I was driven sad by the environment and studies a little bit on <curses.h> library, and demoed the class on Thursday's lab to protect myself from any further suffering. But still, it was just a wrapper of a source library, patent?
4. Compared with a TA for spring semester, I would rather prioritize my time so that I could make good preparation for my job searching, and get graduated smoothly from this department. And that's the reason from very beginning from emacs demo week, unlike Emeth as aggressive as she behaves; I have been completely outside this TA aggressive war. I will get graduated. 
   
   
I got pretty much all Bs from my previous courses, like cs210 programming languages, cs570 AI, EC, which ones that I liked too much, though I did feel very unfair about some of them, like cs210. I wrote a 500 line of Elisp code to make one tic-tac-toe move within my first month here in U of I. But still with limited homework scores, I got B still. With all these grades, I must be very stupid to progress well at all. And on 11/17/2014, fault tolerance, Dr. Krings was saying some minds don't seem to turn around at all. According to all the facts happened during the pass more than two years, it must be especially stupid me that was not able to study well, nothing to do with the instructors, nothing to do with this university at all~

I have been brave to solve my technical problems, but now when I looked back to review this process working with you, and what has happened during the past two years, especially during this year, I felt frightened. I am a girl grown up from the countryside in a developing country with all the suffering during my childhood. I had all my out-of-state tuition fees waved for my Statistics master's degree. How could I ever imagine that I was going to suffer all these discrimination on me, good or bad, all Bs for my courses, separation from the rest majority of classmates and so on? Tortured by personalities like yours, I always suffered from feeling unsafe, and this unsafe feeling dragged my life miserable. If I know any of this detailed information, if we could rewind the time back, I would never want to step into this department ever again! And in the future, if I have any choice, I would not want to come back to this department environment again! 

Up to this point, I wonder how many professors in our department now are still dreaming that I would continue with a Ph.D in this department. We have two Chinese Ph.Ds, Xin and Jia, both of whom chose to stay here for Ph.D without even trying to work in industry by applying OPT. It's their personal choices to stay in UI for Ph.D without OPT after masters, but as clear at this point as we shall all reach and agree, it will never happen on me! I AM GRADUATING in Aug 2015~! No regret, no come back. 

I learned that all the instructors, Professor Bolden, who is the only master's degree instructors here in our department; Dr. Soule, who doesn't necessarily qualify for a Assisted Professor here in UI before, was all completely brought up to be an associate armed with best students during the tenure tracking process, which is similarly happening on another assist professor right now as well . Since all those persons who gave me hard time (Dr. Soule blocked me from having an industry offer which company I have worked for earlier in spring semester by covering cooperative convolution in his EC class during critical decision time) are all appreciate to Dr. Alves-Foss, now I do begin to think if it is the truth that actually it has been Dr. Alves-Foss who designed and directed the whole process of blocking me here in U of I. And also he will be "on war" for coming spring semester for cs210, I will stay tuned, sharp my eyes and ears to see what's Dr. Alves-Foss's opinion on this thing. Will he work hard to block me from graduation, from finding a job, or he may even help me find a job, or could simple just let me go? I look forward to see his response towards this whole thing. 

-- Heyan Huang


* Upcoming CSAC Changes
Pinchuk, Kirsty (kpinchuk@uidaho.edu)
You replied on 11/12/2014 4:30 PM.
Sent:	Wednesday, November 12, 2014 2:57 PM
Cc:	
Donohoe, Gregory (gdonohoe@uidaho.edu)
Good afternoon all,

As you know fall break and Thanksgiving are coming up. At your earliest convenience we will need to know what your intentions are for that week and which shifts you are available for.

We would also like to inform you that after the week of Thanksgiving we will have a new sign in policy in place in the CSAC. Beginning Monday December 1st you will need to come to the front office at the beginning and ending of each of your shifts to sign in and out respectively.
If you have any questions of concerns please feel free to contact me.

Kirsty Pinchuk
Student Coordinator
University of Idaho
Computer Science Department
(208) 885-6592
Moscow, ID 83843-1010

* Potential 2015 Paycheck Changes - University of Idaho Foreign National Data Review (FNIS)
danieln@uidaho.edu [danieln@uidaho.edu]
Sent:	Tuesday, November 11, 2014 4:26 PM
To:	
Huang, Heyan (heyanh@vandals.uidaho.edu)
Dear HEYAN HUANG,

At this time of the year we request that you review your personal and immigration information on file with Human Resources to check for any changes.  Please log in to the Foreign National Information Systems Program (FNIS), review your data on pages 1-5 and make any necessary changes (address, visa status, etc.).  Go to the Confirmation page, (page 6), and click FINISH to submit it.

You can log into FNIS at https://fnis.thomsonreuters.com/uidaho/

Your FNIS username is Huang

Your FNIS password is ldfjdfkl

Please remember to select the Confirmation check box on page 6.  It states, "The information I have entered is correct and I wish to submit it to my host site. Then select the Finish button in the lower right-hand corner.  The system will state Information Received and give you an option to click on a link to send an e-mail to notify me that it is complete.

The information gathered through FNIS will determine tax withholding status affecting your paychecks for 2015.  If there are any changes, you may need to visit Human Resources to sign a new W-4 Form and/or Tax Treaty.  The deadline for completion of FNIS is Friday, November 21, 2014.  By meeting this deadline, you will affect your first paycheck in 2015 (Jan. 2, 2015).  Forms received after November 21, 2014, will still be processed to affect future paychecks.

If you have any questions regarding your password or any other issues, please contact me at 885-3677 or danieln@uidaho.edu

Thank you,
Dan

* [Csgrads] Added course offering: CS 328 for Spring 2015
csgrads-bounces@uidaho.edu [csgrads-bounces@uidaho.edu] on behalf of Jeffery, Clint (jefferyc@uidaho.edu) [jefferyc@uidaho.edu]
Sent:	Saturday, November 08, 2014 12:58 AM
To:	
Mailman - csugrads@uidaho.edu; Mailman - csgrads@uidaho.edu
Cc:	
Bolden, Bruce (bruceb@uidaho.edu); Donohoe, Gregory (gdonohoe@uidaho.edu)
Attachments:	
ATT00001.txt (450 B)
Dear CS Students,

Thanks to an administrative feat of no small merit, a section of CS 328, Introduction to Computer Game Development, has been added for Spring 2015. The course will be T/Th at 12:30. Since this is a late addition I thought I had better let you all know.

I note that CS 324, Computer Graphics, is also being offered this Spring, and I highly recommend it.  Computer Graphics is not a prerequisite for CS 328, but most computer games are graphical and the two courses go very well together. CS 328 will be easier and more fun if you have done some computer graphics programming before, or are taking CS 324 concurrently. CS 324 and CS 328 are both prerequisites for the CS 428/528 Multi-User Games and Virtual Environments course, if you may want to take that down the road.

I am happy to answer questions by e-mail.

Warm Regards,
Dr. J

* [Senior Design] Team Issues
Bolden, Bruce (bruceb@uidaho.edu)
You replied on 11/6/2014 12:06 PM.
Sent:	Thursday, November 06, 2014 11:27 AM
To:	
Huang, Heyan (heyanh@vandals.uidaho.edu)

Heyan,

I'd like to have a little chat with you.  It sounds like a small misunderstanding
between you and the rest of your team has occurred and that it is growing
into a bigger problem.

I will be in my office from 1:30--3:00 PM.

Bruce

* RE: TA Appointment for Spring
Huang, Heyan (heyanh@vandals.uidaho.edu)
Sent:	Wednesday, November 05, 2014 4:12 PM
To:	
Pinchuk, Kirsty (kpinchuk@uidaho.edu)
Good Afternoon, Kirsty, 

I know that we have lots of students that are interested in the TA position in our department, and I may lose it eventually, but to think about it positively, I do need to express in this important email that, I AM interested in the spring semester's TA position to support my tuition fees and living expense, and my medical bills and potential medical expenses as well (I know I have important health problems and I have not start to work on it yet~). 

We all don't know about the results yet, but by sending out this email, please help consider me as a spring semester TA candidate as well. 

thanks,
-heyan

* TA Appointment for Spring
Pinchuk, Kirsty (kpinchuk@uidaho.edu)
You replied on 11/5/2014 4:12 PM.
Sent:	Wednesday, November 05, 2014 3:27 PM
Good Afternoon,

As you know the fall semester is coming to an end and it is time to start thinking about Spring Semester.

I need to know if you would like to continue your current TA position with the department. It is important that you express our interest quickly, so If I do not hear back from you by 5pm tomorrow November 6, I will assume that you are not interested in continuing your appointment next semester and will award it to another student.

Thank you.

Kirsty Pinchuk
Student Coordinator
University of Idaho
Computer Science Department
(208) 885-6592
Moscow, ID 83843-1010

* [Engineering Students] Careers in patents for engineers and	scientists, U of I, Nov. 5
engineering-students-bounces@uidaho.edu [engineering-students-bounces@uidaho.edu] on behalf of Leija, Thomas (thomasl@uidaho.edu) [thomasl@uidaho.edu]
Sent:	Monday, November 03, 2014 11:36 AM
To:	
Mailman - engineering-students@uidaho.edu
Will you please forward the following information to the various departments within the College of Engineering?

Thank you,

Thomas Leija
Career Center
University of Idaho

If you have (or will soon have) a degree in engineering, computer sciences, or the hard sciences (chemistry, biology, physics and related disciplines), you can take the Patent Offices Registration Exam to become a Patent Agent. Patent agents can make up to $20,000 a year more than similarly situated engineers and scientists. The Exam is available virtually on-demand via computer. Becoming a patent agent can also be a step toward the even more lucrative career of becoming a Patent Attorney.
If this sounds intriguing, come join Practicing Law Institute (PLI) for a presentation by Mark Dighton, PLI's Director of Law School Relations and a Director of their Patent Office Exam Course. Topics for discussion include:
·         Careers for patent agents (what the work is like and where you find it), and
·         The latest info on the Patent Offices Registration Exam (who can take it, how it works, and recommendations on how to study for this very difficult Exam).
Date:     Wednesday, November 5th
Time:     5 pm
Location: ALB 101
Please visit us on the Web for a wealth of information on the resources we offer:
www.PatentOfficeExamCourse       [www.pli.edu]www.pli.edu

Mark Dighton, Esq.
Director of Law School Relations and Admin. Director, Patent Office Exam Course
PLI (Practising Law Institute)
212-824-5841
mdighton@pli.edu

* Hello Tower iLLuminati, 

I am sorry for what I have brought to confused us during last night's email and this mornings' one concerning about Emeth's TA part. I apologize for that. I never mean to attack Emeth at all, if she feels I was attacking, it is not my intention. 

I can be open-minded to consider this time Emeth's lie to be hers "trying to be considerate" good manner. But at the same time, I did still feel very bad about Tuesday's meeting and team environment, and I consider it was mainly Emeth's fault -- who is the team manager and who supposed to be able to handle this case well. 

I don't know if all of you guys consider this about the same way, but just as I mentioned to some friend earlier, in our culture, we believe there is a perfect god's mind live in every alive human beings, and I believe what you declared. So what happened during the 2.5 hours, I don't even try to think and be judgmental at all. But at the same time, please also try to understand my consideration for Emeth. I was kind enough to remind her about her influence because Tuesday's meeting exposed her weakness, and I want her to perform good and our department to be good as well if anything matters and affected. 

At this point, I can't consider Emeth to be a good team leader, but try not to make this too much a big deal, and also for my last year's sake, I can tolerant it. I will try my best to cooperate with all of us together, and I deserve all other team members to treat us in appropriate manner as well. 

I thought my mornings' email should be the last one, didn't realize there came two more. I don't think I will reply any more before meeting. Let's hope we make a good meet today.

thanks,
heyan

* Re: Team Meeting 3:30
Bailey, Paul (bail1806@vandals.uidaho.edu)
Sent:	Thursday, November 06, 2014 10:22 AM
To:	
Thompson, Emeth (thom5468@vandals.uidaho.edu); Huang, Heyan (heyanh@vandals.uidaho.edu); Brown, Matthew (matt2714@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu)
Heyan and Emeth,

Relax, we are a team and we are all on track to meet our goals that have been outlined. There has obviously been some miscommunication among some members, which is understandable considering we have a larger team whose members have dramatically different lives and schedules. 

On a side note: Since this topic was mentioned below... In terms of our Software Engineering class a few semesters back, I do not agree that I did "very little work". However, I will agree that when comparing my contribution to that particular project during that semester, there were many other students who invested a much larger portion of their time into the project. So in comparison, I did less work than some others, but in no way did I do "very little work". I did do my part in that project, and I completed everything that I was tasked with for that project,  just as I am doing my part in this project. I am sure there is some point that Emeth was trying to make in bringing that up, and that is fine. I am not offended by it, I just wanted to clarify that portion since this has turned into a public document. 

Emeth and Heyan, you are both valuable members to the team. I really think that this has been a big misunderstanding. I am sure we can work out our differences and continue to make progress on this project. 

Paul.

* Re: Team Meeting 3:30
Thompson, Emeth (thom5468@vandals.uidaho.edu)
Sent:	Thursday, November 06, 2014 10:15 AM
To:	
Huang, Heyan (heyanh@vandals.uidaho.edu); Brown, Matthew (matt2714@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu); Bailey, Paul (bail1806@vandals.uidaho.edu)
Heyan,

Stop personally attacking me through email. Our senior design group has nothing to do with my TA position and your opinion of my personality or how it reflects on the CS department. If you want to discuss these things then you need to email me and not the whole group. I mentioned that if there are actions that I do that disrupt our ability to work together then tell me what those are. I can change how I interact with the group to enable a better working environment. Obviously, lying is something you have zero tolerance for and I will do my best to ensure that my communications are understood not thought of as lies. 

I did mention that you feel disrespected in my past email and I understand why. You are upset because you feel lied to, but the problem isn't that I lied to be malicious and make you feel left out. It was just a poor word choice. I said "the meeting was about 15 minutes" what I should have said and what I really meant was "we worked for about 15 minutes". Ranger and Matt worked later than everyone else and 2.5 hours only applies to them not the whole meeting. 

Again, please restrict your communication to the group to topics that relate to the project not to me personally.

Emeth Thompson

* Hello Emeth,

I had bad personal experience towards lies, and I have absolutely zero tolerance towards lies ever since. And I hate to be in the situation being suspected that I lied when actually I didn't. And that was the reason your lie triggered all my seisitivity and bad feeling towards you yesterday. And from your reply, at least, you and I didn't run into the corner that without email record, each of us deny on everything, which is good news for us. At least as this point, I can calm down.

It was your fault on Tuesday as the project manager didn't notify the meeting and didn't remind me about the meeting through email, and the team member didn't offer any kind reminder neither. And your email and coldness on Tuesday did surprise me, and make me feel disrespected, and you seemed not realizing this fact yet, but we can discuss about it all together today. 

Emeth, please realize that as the only undergraduate TA in the CS department, you have deep and wide influence on students here. In the student's eyes, as the only undergraduate TA, you are the representive and influence of the department, please behave properly so that the department's reputation won't get damaged by you. 

I have no experience lied by any other classmates here in US so far yet rather than you. I never know that people, students, project managers can lie this way yet until yesterday. And that's the reason yesterday I couldn't calm down at all. Let's prepare and expect an effective and productive meeting today then to solve the problems. 

Heyan

* Re: Team Meeting 3:30
Thompson, Emeth (thom5468@vandals.uidaho.edu)
Sent:	Thursday, November 06, 2014 2:44 AM
To:	
Huang, Heyan (heyanh@vandals.uidaho.edu); Brown, Matthew (matt2714@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu); Bailey, Paul (bail1806@vandals.uidaho.edu)
Well everybody, we got stuff to talk about tomorrow. 

For the record:
1) I did say that Ranger wouldn't check a posted schedule if we had one. My experience with Ranger has been that he prefers verbal interaction over emails and documents. If we are going to devote time and resources to a making a calendar then we need to be sure that it will get used. If it is not used then it just becomes more busy work that nobody has time for. 
2) I did say that Paul did not do very much work for our Software Engineering project and Paul will probably agree. I was telling Heyan this because I want everyone to contribute to this project. We are all very busy and I don't want anyone to end up having to do more than their fair share.
3) I did say the meeting was about 15 minutes. This was an exaggeration because the group was mostly unproductive for the first hour. Pretty much the only members who got anything done was Matt and Ranger and they were the ones who worked late. Paul and I were there till about 3:50 (im not sure the exact time we left). 15 minutes is literally a lie that was meant to reflect our productivity. From now on i will be more specific so that there isn't any confusion.
4) I do have an aggressive and superficial personality. Ranger refers to me as "cold-hearted" and this does not bother me. If there are specific things I do that are aggressive and cause disruption, then I want to hear about this because I'm probably not aware that I'm doing it.
   
What is important is that we resolve problems where the group is unable to work together in a respectful manner. I think we have had some misunderstandings, miscommunications, and a lack of organization. This has resulted in Heyan feeling disrespected and we should all do what is reasonable to resolve this. What is considered reasonable can be discussed tomorrow. If anyone else feels that another member of the group has been disrespectful then tomorrow is the day to talk about it. 

Emeth Thompson

* Hello Emeth, 

When I received your email yesterday, once I finished my wiki page bio, I replied to you as soon as possible within 2 hours. I didn't hear back from you until today around 2:30pm after your compiler class, you stopped by the office and hurry to grab your water bottle and we chatted for about 5 minutes. You declared it was just a short meeting lasted around 15 minutes and I didn't feel too bad about it at that time. You refused to use Google calender because you felt Ranger is the one won't check it; And you insisted to send us email reminders because you need to remind Ranger any way. Then you asked me questions about my hearing, and which sounds I have difficulties, I answered overall in general I am OK, but subtle difference like th /f/ /tf/ I have some difficulty to differentiate and pronounce correctly. 

I can't feel as comfortable any more when I talked to Matt in CSAC and received your email today. I can't imagine, as a american student, how could you possibly confuse 2.5 hours (from 2:30 to around 5:00pm according to Matt) to be 15 minutes? Just as I feel surprised yesterday receiving your email, your attitude in that email, you avoid reply to me through email and talked to me instead, your today's email completely ignoring yesterday's matter, and emphasize the "grades" and "reply to all on email" thing, all together does make me feel bad now. It feels like I haven't done anything and I don't deserve a good grade, and maybe I should be ignored or dismissed from this team. 

Let's be frank and face it. You mentioned that during your software engineer class Paul seemed to be the one didn't do anything, I answered that as a sub-team Paul and I are OK, we don't have such a problem. 
Since you lied on 2.5 hours, if you are actually talking about me, at least when you asked me to type the team contract when no other members have any assignments, as the only international in the team who may have difficulties on language part later on, I did it without any word; 
on 10/23 team meeting, you declared to work on wiki page, Paul and I declared for GUI; GUI is due on 11/11, wiki was yesterday, and I showed you from my laptop on 10/31 Friday in CSAC when you entered that I was working on Qt creator GUI interface, I showed you the form I was working on with Josh and other students together in CSAC; But on yesterday's wiki due day, you made such a thing. 
On 10/2 you and I spent 1 hour to review and make necessary contents and format updates on team contract in our office using my laptop and Emacs; on 10/3 you sent out email declared you changed document font size from 10pt to 12pt, and I ended up change it back to 11pt without sending emails; 
As you talked to me having seen how efficient I used Emacs and org-mode for latex, you asked me to be the person responsible for the design documents. In the followed team meeting, I specified that I haven't taken software engineer in regular class, not that confident about document contents, and we as a team agreed that, we all are responsible for the contents, and I will be the person to integrate and organize them to be good latex documents, with review like you and I did  already for team contract, because by that time all you four will be berried with heavy duty compiler homework. 
And I am ok that I will be dragged behind for project implementations when all you four have heavy compiler duties, and we plan to get only the GUI interface implementations ready without linking the button functionality. Assigned to be the secondary Lead Programmer in the contract, with the primary one Ranger will focus on his compiler, I will still be the primary responsible person for GUI interface implementations. 


I may have listed too much already. Above all, I am the only person in CSAC who needs to start 3 mornings from 8:00am, and Matt was the only person among those I asked who was willing to exchange one hours with me so that on Thursday mornings I don't have to wake up early, and he and I don't have any say sorry issue. You lied or not, Paul and Ranger could still be the judge. Since when I talked to Matt today he mentioned "We don't like stay here in CSAC", I think I have 2 main concern/issue here:

1. On tomorrow's meeting, we need settle down this "Tuesday meeting time and reminder" thing. I don't like working in CSAC while having meeting neither. So we need discuss about this;
   
2. For Emeth only: 
I should have graduated this May already because Dr. Jeffery and I have 2 year oral graduation agreement but I was blocked by the department for one more year, together with my medical problems, just so that it will make other students (like international ph.d students) feel better because my cs master's degree without a CS undergraduate processed too well under this 4.5 to 5 years on average bachelor's degree environment. For the passed more than two years, I am mature enough to know clearly my goals, and I worked hard and can bear whatever situation the department have possibly cast on me. I appreciate that the department gives me the opportunity for TA for this fall semester. I expressed my expectation for next semester, but I wouldn't demand it, and it's up to the department to decide who they select for TAs. And to my understanding, you got this semester's one special section TA was only because your husband was willing to accompany you to stay on campus for one more year, and you may not qualify for the TA yet because you haven't even finish compiler yet. And it was you not your husband was because you are the superficial one and can be induced to behave the way they expect. 
Unless you are especially cultivated as a "spy" by the department to dismiss discrimination on international students signal, if that's the case, simply ignore my email, you will have your destination; Otherwise, you need pay attention to your personality. We have every reason to prevent yesterday's thing to happen, but it happened (we skipped one meeting during your compiler exam week; you all didn't appear in CSAC yesterday as regularly did; you all didn't offer email or phone call reminder; and you lied); as the project manager, I replied to your email yesterday, but you didn't reply; And you lied to me today with later on your email mentioned nothing about Tuesday's meeting. 
The only possible reason I can possibly think that you behavior so wired recently (say things on last Friday's meeting, make such an attitude yesterday, and lie to me today) is that you are very aggressive, and worked too hard just for a TA opportunity. I wondered why you can't figure out the questions your two female students have on Lab7 or Assignment 7, and needed your husband to help you out in CSAC the other day. Now I think I have the answer. Keep sending emails out for senior design course and registering Dr. Soule's Video Games and Evolution course doesn't necessarily guarantee an A nor your TA position, but by correcting your personality and stopping being superficial and practice more can help you go a long way. I just had a sorry from you recently, and I don't need that word any more. I state this out sincerely just for your own good. 


I never want to make anything a big deal, but your 2.5 hours lie to be 15 minutes did challenge my bottom line. Since Dr. Soule treats you especially well, I struggled whole evening ever since I read the email to think if I should state it out, should I or shouldn't I send out this email? If I did become very sensitive and did make it a too much big deal by the environmental force recently, like suddenly on this Tuesday's lab, there were several students trying so hard to make me behave ugly, if that's the case, please ignore the email and forgive me. 

Sincerely, 
Heyan

* Team Meeting 3:30
Thompson, Emeth (thom5468@vandals.uidaho.edu)
Sent:	Wednesday, November 05, 2014 3:44 PM
To:	
Huang, Heyan (heyanh@vandals.uidaho.edu); Brown, Matthew (matt2714@vandals.uidaho.edu); Thompson, Emeth (thom5468@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu); Bailey, Paul (bail1806@vandals.uidaho.edu)
Hello Tower iLLuminati,

Just a reminder we have a meeting tomorrow at 3:30. This meeting will be in Matt's office unless it is unavailable. During the meeting we will prepare a plan for the information we want to share during the design review. Though Bolden said we should just talk about the "big-picture" features, i think we still try to match our presentation to the grade sheet requirements. Ranger will be our presenter for the design review but we should all agree upon the content since its all of our grades.

If someone is unable to make it to the meeting then please reply to all on this email. 

Thank you,
Emeth Thompson

* RE: Senior Design Meeting
Huang, Heyan (heyanh@vandals.uidaho.edu)
Sent:	Tuesday, November 04, 2014 8:10 PM
To:	
Thompson, Emeth (thom5468@vandals.uidaho.edu)
Cc:	
Brown, Matthew [matt2714@vandals.uidaho.edu]; Adams, Ranger [adam6860@vandals.uidaho.edu]; Bailey, Paul [bail1806@vandals.uidaho.edu]
Hello Emeth, 

I am sorry to say that I missed today's meeting without notification. This is my first time missed a meeting. As an "environmental-friendly" team, I hope later on if such things happen, a short one sentence email reminder could help, and hoping that later on whoever is missing or late, we could do the same thing. 

Though you declared it's a short meeting, the statement and attitude about the meeting contents still surprised me a little bit. I am currently working on the GUI Qt Creator Interface as we have assigned about a week ago, and I will meet Paul to discuss and finish our subteam's GUI design and documentation. Since Paul has added the GUI image into wiki already, I simply added my little bio-:)

By the way, are we suppose to meet this Thursday for our team member meeting, or it's always consistent on Tuesday afternoon at 2:30 (and I need to stay in CSAC from 2:30-3:30 on Tuesday, but available on Thursday 2:30-3:30, as you already knows)? And later on if we do use the 2:30-3:30 Tuesday one hour, I hope we can do it in CSAC, or we find some other hour so that I can join. 

thanks,
Heyan

* Hello Emeth, 

I am sorry to say that I missed today's meeting without notification. This is my first time missed a meeting. As an "environmental-friendly" team, I hope later on if such things happen, a short one sentence email reminder could help, and hoping that later on whoever is missing or late, we could do the same thing. 

Though you declared it's a short meeting, the statement and attitude about the meeting contents still surprised me a little bit. I am currently working on the GUI Qt Creator Interface as we have assigned about a week ago, and I will meet Paul to discuss and finish our subteam's GUI design and documentation. Since Paul has added the GUI image into wiki already, I simply added my little bio-:)

By the way, are we suppose to meet this Thursday for our team member meeting, or it's always consistent on Tuesday afternoon at 2:30 (and I need to stay in CSAC from 2:30-3:30 on Tuesday, but available on Thursday 2:30-3:30, as you already knows)? And later on if we do use the 2:30-3:30 Tuesday one hour, I hope we can do it in CSAC, or we find some other hour so that I can join. 

thanks,
Heyan

* Senior Design Meeting
Thompson, Emeth (thom5468@vandals.uidaho.edu)
Sent:	Tuesday, November 04, 2014 6:10 PM
To:	
Huang, Heyan (heyanh@vandals.uidaho.edu)
Cc:	
Brown, Matthew (matt2714@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu); Bailey, Paul (bail1806@vandals.uidaho.edu)
Hello Heyan,

Today for senior design we had a short meeting where we cleared up some confusion about the GUI design. The grid which is the main work area will be static. i.e. it will not move and all squares in the grid will always show. The frame, which represents the light shows display area will be a movable object. In Paul's GUI design the grid is the gray squares and the frame is the orange squares. When the project is complete, the user will be able to fill in the grid however they want and they will use the frame to capture sections of the grid as frames in the light show.  

Also, we all need to write a short bio for ourselves to put on our project's wiki page:

http://mindworks.shoutwiki.com/wiki/Tower_Lights_Animator

If you would like to edit your bio yourself then you should make an account at the wiki and edit the table listed under the  Team Members section. If you would rather me edit it then please reply to this email with the bio you would like to include. 

Emeth Thompson

* RE: lab 7 8 9 rubrics
Soule, Terence (tsoule@uidaho.edu)
Sent:	Monday, October 27, 2014 4:09 PM
To:	
Huang, Heyan (heyanh@vandals.uidaho.edu); Rinker, Robert (rinker@uidaho.edu); Thompson, Emeth (thom5468@vandals.uidaho.edu); Chitrakar, Anup (chit8942@vandals.uidaho.edu); Rubini, Joshua (rubi4714@vandals.uidaho.edu)
Attachments:	
rubricAssign7.pdf (28 KB)[Preview on web]; rubricAssign8.pdf (30 KB)[Preview on web]; rubricLab6.pdf (27 KB)[Preview on web]; rubricLab7.pdf(27 KB)[Preview on web]; rubricLab8.pdf(26 KB)[Preview on web]
Hi,

I did forget to send rubrics. They are attached for the recent labs and assignments.   At this point I suspect that you can do a perfectly fine job of grading on your own.  So, if I get behind on the rubrics feel free to go ahead and grade without them (or remind me to send them).

Thanks,
Terry


-----Original Message-----
From: Huang, Heyan (heyanh@vandals.uidaho.edu) 
Sent: Monday, October 27, 2014 2:00 PM
To: Rinker, Robert (rinker@uidaho.edu); Soule, Terence (tsoule@uidaho.edu); Thompson, Emeth (thom5468@vandals.uidaho.edu); Chitrakar, Anup (chit8942@vandals.uidaho.edu); Rubini, Joshua (rubi4714@vandals.uidaho.edu)
Subject: lab 7 8 9 rubrics

Dr. Soule, 

I think from Lab1 you begin to send lab rubrics for us to use. By default I always thought we, as the TA should grade according to your reqirements, and I did grade all the previous using the rubrics. But maybe I forgot to ask the question that do you need us to grade using this rubrics sheet, or maybe you don't care that much? Can we grade without using these rubrics, or we'd better use the rubrics before we grade any lab or homework? I feel I got confused. If you do want us to grade using the rubrics, please help send the grading rubrics for Lab7 and Lab8. I feel I don't know how the students are performing now towrads arrays and objects. And I think you simply forgot this rubrics thing. 

thanks,
heyan

* Re: CS499 class today and html Grade display
Huang, Heyan (heyanh@vandals.uidaho.edu)
Sent:	Tuesday, October 14, 2014 1:01 AM
To:	
Jeffery, Clint (jefferyc@uidaho.edu)
Yes, please make it private or simply send email to us so we know among us three. Thanks.

* Re: CS499 class today and html Grade display
Jeffery, Clint (jefferyc@uidaho.edu)
You replied on 10/14/2014 1:01 AM.
Sent:	Tuesday, October 14, 2014 12:45 AM
To:	
Huang, Heyan (heyanh@vandals.uidaho.edu)
Heyan,

I am not aware of having put performance online.  If you mean my record of what we are doing, OK then I will make that file private. It did not contain grades, but it did contain a summary of some of the things we have done so far.

Thursday office hours is a share item and probably not the best time if you want a whole hour, but it might be fine for stopping my for a few minutes and discussing where you are at.

Dr. J

* CS499 class today and html Grade display
Huang, Heyan (heyanh@vandals.uidaho.edu)
You forwarded this message on 10/13/2014 11:53 PM.
Sent:	Monday, October 13, 2014 11:50 PM
To:	
Jeffery, Clint (jefferyc@uidaho.edu); Mendes Costa, Gleidson [mend8916@vandals.uidaho.edu]
Dear Dr. Jeffery, 

Sorry that I missed today's class, I thought today's class was cancelled or something. I will go to Thursday's 2:30-3:30pm your office hour to discuss about this class and today's missed class contents, or I will try to schedule a time to meet you if I am not allowed to occupy your other class' office hour time. 

And one more thing I want to mention is that, I don't think it is an appropriate way/manner to put our performance online, even we have only two classmates. I know most of the instructors won't share student's grades with other classmates, and I don't remember I have any instructor who have ever put student's performance online. So I am wondering if you really think this is reasonable or just put there by mistake. 

I look forward to hearing from you. 

Sincerely,
-heyan

* RE: Tower Animator _ Simple GUI Interface
Huang, Heyan (heyanh@vandals.uidaho.edu)
Sent:	Friday, October 10, 2014 8:06 PM
To:	
Thompson, Emeth (thom5468@vandals.uidaho.edu); Brown, Matthew [matt2714@vandals.uidaho.edu]; Thompson, Emeth [thom5468@vandals.uidaho.edu]; Adams, Ranger [adam6860@vandals.uidaho.edu]; Bailey, Paul [bail1806@vandals.uidaho.edu]
Attachments:	
Screenshot from 2014-10-10~1.png (17 KB)
hi guys, 

now i believe Matt is correct, Qt thing is really not that hard. I have worked two hours on it today and got a simply menu bar interface. 
I attached it in case anybody else except me think maybe we could go ahead and create a simply interface for our Snapshot day. 

Let me know any ideas you have about interface, and according to your response, let's see if we need to target make any progress this weekend. 

thanks,
heyan

* RE: Tower Animator _GUI Interface
Huang, Heyan (heyanh@vandals.uidaho.edu)
You replied on 10/10/2014 8:06 PM.
Sent:	Friday, October 10, 2014 4:52 PM
To:	
Thompson, Emeth (thom5468@vandals.uidaho.edu); Brown, Matthew [matt2714@vandals.uidaho.edu]; Thompson, Emeth [thom5468@vandals.uidaho.edu]; Adams, Ranger [adam6860@vandals.uidaho.edu]; Bailey, Paul [bail1806@vandals.uidaho.edu]
I want to get access to the interface the other day Dr. Rinker has showed us when we have our client meeting. I know some of you have that interface, I tried in CSAC to load that .vcproj file, it built but failed to get the GUI interface. 

Anybody can help give simple instruction how to access and get the interface, or at least help attach an interface snapshot?

Feels like we still get lots of things to do for the Snapshot day. Let me know if we need to gather together to prepare something materials. 

thanks,
heyan
________________________________________
From: Thompson, Emeth (thom5468@vandals.uidaho.edu)
Sent: Friday, October 03, 2014 1:29 PM
To: Bolden, Bruce (bruceb@uidaho.edu)
Cc: Huang, Heyan (heyanh@vandals.uidaho.edu); Brown, Matthew (matt2714@vandals.uidaho.edu); Thompson, Emeth (thom5468@vandals.uidaho.edu); Adams, Ranger (adam6860@vandals.uidaho.edu); Bailey, Paul (bail1806@vandals.uidaho.edu)
Subject: Re: Tower Animator - Team Contract

I have attached the LaTeX version of our team contract. I changed the font size to 12pt and also altered some copy/paste errors.


Emeth Thompson

&

Tower iLLuminait
